id: P001837
initial_creation_type: ocr
source_metadata:
  id: bdr:W24827
  title: གཅེས་བསྡུས་འཆི་མེད་ནོར་བུའི་ཕྲེང་བ།
  author: ''
  volumes:
    ca93658ff80f4bac830b0db8d3f1a460:
      image_group_id: I1KG23206
      title: ''
      volume_number: 1
      total_pages: 174
